//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.OrdenDeTrabajo = new HashSet<OrdenDeTrabajo>();
        }
    
        public int ID { get; set; }
        public long DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Telefono1 { get; set; }
        public Nullable<long> Telefono2 { get; set; }
        public Nullable<long> Telefono3 { get; set; }
        public string Email { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDeTrabajo> OrdenDeTrabajo { get; set; }
    }
}
