//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDeTrabajo
    {
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaProblableEntrega { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int TipoEstadoID { get; set; }
        public int TipoEquipoID { get; set; }
        public int TipoMarcaID { get; set; }
        public string Caracteristicas { get; set; }
        public int TipoTrabajoID { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TipoEquipo TipoEquipo { get; set; }
        public virtual TipoEstado TipoEstado { get; set; }
        public virtual TipoMarca TipoMarca { get; set; }
        public virtual TipoTrabajo TipoTrabajo { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
